In [1]:
import pandas as pd
import numpy as np

In [31]:
df = pd.read_csv('AI_Impact_on_Jobs_2030.csv')
print(df)

     Employee_ID              Job_Title    Industry    Country  \
0     AIJ-100000          Data Engineer  Healthcare      Japan
1     AIJ-100001     Healthcare Analyst      Retail         UK
2     AIJ-100002          HR Specialist   Education     Canada
3     AIJ-100003  Cybersecurity Analyst  Government         UK
4     AIJ-100004     Healthcare Analyst   Education        UAE
...          ...                    ...         ...        ...
2995  AIJ-102995         Data Scientist   Education      India
2996  AIJ-102996          Data Engineer  Healthcare        UAE
2997  AIJ-102997        DevOps Engineer      Energy   Pakistan
2998  AIJ-102998         Data Scientist  Government  Australia
2999  AIJ-102999          HR Specialist      Retail    Germany

     Education_Level  Years_Experience  AI_Replacement_Risk  \
0                PhD                 1                 0.25
1           Bachelor                24                 0.73
2        High School                21                 0.80
3           Bachelor                 5                 0.29
4                PhD                20                 0.11
...              ...               ...                  ...
2995        Bachelor                 0                 0.62
2996             PhD                 4                 0.52
2997     High School                 7                 0.72
2998        Bachelor                19                 0.82
2999          Master                 9                 0.68

      Future_Demand_Score Remote_Work_Possibility  Average_Salary_USD  \
0                    0.78                     Yes              207392
1                    0.33                      No              140785
2                    0.69                     Yes              124800
3                    0.94                      No              199878
4                    0.92                      No              178682
...                   ...                     ...                 ...
2995                 0.27                  Hybrid              202565
2996                 0.57                     Yes               37215
2997                 0.70                      No               55179
2998                 0.76                  Hybrid              125291
2999                 0.44                      No              152792

                                        Required_Skills Automation_Level  \
0                  Python, Communication, Deep Learning              Low
1     Deep Learning, Azure, Communication, TensorFlo...              Low
2     Kubernetes, Cloud Computing, TensorFlow, SQL, ...           Medium
3     Excel, Kubernetes, Prompt Engineering, Leadership           Medium
4            SQL, Leadership, TensorFlow, Cybersecurity              Low
...                                                 ...              ...
2995  Azure, Project Management, Cloud Computing, Cy...           Medium
2996                     Communication, PyTorch, Docker              Low
2997                  TensorFlow, Excel, Python, Docker           Medium
2998      Cybersecurity, Cloud Computing, Deep Learning           Medium
2999           Kubernetes, Cybersecurity, Communication              Low

      Job_Growth_2030  Work_Hours_Per_Week Company_Size AI_Tool_Usage  \
0                   3                   37   Enterprise          High
1                  -5                   42      Startup      Moderate
2                  -5                   57      Startup           Low
3                   7                   59   Enterprise          High
4                   6                   34      Startup          High
...               ...                  ...          ...           ...
2995               36                   59   Enterprise      Moderate
2996               17                   45      Startup           Low
2997               34                   35      Startup           Low
2998               21                   47      Startup      Moderate
2999               32                   44       Medium      Moderate

      Performance_Score Upskilling_Needed  Job_Satisfaction Hiring_Trend_2026
0                  2.08               Yes              3.86           Growing
1                  4.54                No              4.23           Growing
2                  3.14                No              3.54            Stable
3                  3.67                No              4.37         Declining
4                  3.68                No              3.99            Stable
...                 ...               ...               ...               ...
2995               4.54               Yes              1.27            Stable
2996               2.71                No              2.56            Stable
2997               4.88               Yes              3.17         Declining
2998               3.59               Yes              3.78            Stable
2999               3.29                No              1.36           Growing

[3000 rows x 20 columns]

In [32]:
df.head()

,Employee_ID,Job_Title,Industry,Country,Education_Level,Years_Experience,AI_Replacement_Risk,Future_Demand_Score,Remote_Work_Possibility,Average_Salary_USD,Required_Skills,Automation_Level,Job_Growth_2030,Work_Hours_Per_Week,Company_Size,AI_Tool_Usage,Performance_Score,Upskilling_Needed,Job_Satisfaction,Hiring_Trend_2026
0,AIJ-100000,Data Engineer,Healthcare,Japan,PhD,1,0.25,0.78,Yes,207392,"Python, Communication, Deep Learning",Low,3,37,Enterprise,High,2.08,Yes,3.86,Growing
1,AIJ-100001,Healthcare Analyst,Retail,UK,Bachelor,24,0.73,0.33,No,140785,"Deep Learning, Azure, Communication, TensorFlo...",Low,-5,42,Startup,Moderate,4.54,No,4.23,Growing
2,AIJ-100002,HR Specialist,Education,Canada,High School,21,0.80,0.69,Yes,124800,"Kubernetes, Cloud Computing, TensorFlow, SQL, ...",Medium,-5,57,Startup,Low,3.14,No,3.54,Stable
3,AIJ-100003,Cybersecurity Analyst,Government,UK,Bachelor,5,0.29,0.94,No,199878,"Excel, Kubernetes, Prompt Engineering, Leadership",Medium,7,59,Enterprise,High,3.67,No,4.37,Declining
4,AIJ-100004,Healthcare Analyst,Education,UAE,PhD,20,0.11,0.92,No,178682,"SQL, Leadership, TensorFlow, Cybersecurity",Low,6,34,Startup,High,3.68,No,3.99,Stable

In [33]:
df.tail()

,Employee_ID,Job_Title,Industry,Country,Education_Level,Years_Experience,AI_Replacement_Risk,Future_Demand_Score,Remote_Work_Possibility,Average_Salary_USD,Required_Skills,Automation_Level,Job_Growth_2030,Work_Hours_Per_Week,Company_Size,AI_Tool_Usage,Performance_Score,Upskilling_Needed,Job_Satisfaction,Hiring_Trend_2026
2995,AIJ-102995,Data Scientist,Education,India,Bachelor,0,0.62,0.27,Hybrid,202565,"Azure, Project Management, Cloud Computing, Cy...",Medium,36,59,Enterprise,Moderate,4.54,Yes,1.27,Stable
2996,AIJ-102996,Data Engineer,Healthcare,UAE,PhD,4,0.52,0.57,Yes,37215,"Communication, PyTorch, Docker",Low,17,45,Startup,Low,2.71,No,2.56,Stable
2997,AIJ-102997,DevOps Engineer,Energy,Pakistan,High School,7,0.72,0.70,No,55179,"TensorFlow, Excel, Python, Docker",Medium,34,35,Startup,Low,4.88,Yes,3.17,Declining
2998,AIJ-102998,Data Scientist,Government,Australia,Bachelor,19,0.82,0.76,Hybrid,125291,"Cybersecurity, Cloud Computing, Deep Learning",Medium,21,47,Startup,Moderate,3.59,Yes,3.78,Stable
2999,AIJ-102999,HR Specialist,Retail,Germany,Master,9,0.68,0.44,No,152792,"Kubernetes, Cybersecurity, Communication",Low,32,44,Medium,Moderate,3.29,No,1.36,Growing

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Employee_ID              3000 non-null   object
 1   Job_Title                3000 non-null   object
 2   Industry                 3000 non-null   object
 3   Country                  3000 non-null   object
 4   Education_Level          3000 non-null   object
 5   Years_Experience         3000 non-null   int64
 6   AI_Replacement_Risk      3000 non-null   float64
 7   Future_Demand_Score      3000 non-null   float64
 8   Remote_Work_Possibility  3000 non-null   object
 9   Average_Salary_USD       3000 non-null   int64
 10  Required_Skills          3000 non-null   object
 11  Automation_Level         3000 non-null   object
 12  Job_Growth_2030          3000 non-null   int64
 13  Work_Hours_Per_Week      3000 non-null   int64
 14  Company_Size             3000 non-null   object
 15  AI_Tool_Usage            3000 non-null   object
 16  Performance_Score        3000 non-null   float64
 17  Upskilling_Needed        3000 non-null   object
 18  Job_Satisfaction         3000 non-null   float64
 19  Hiring_Trend_2026        3000 non-null   object
dtypes: float64(4), int64(4), object(12)
memory usage: 468.9+ KB

In [35]:
df.describe()

,Years_Experience,AI_Replacement_Risk,Future_Demand_Score,Average_Salary_USD,Job_Growth_2030,Work_Hours_Per_Week,Performance_Score,Job_Satisfaction
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,12.383000,0.502910,0.601203,126641.746667,17.238333,44.773333,3.514643,3.026167
std,7.528958,0.261293,0.226674,55405.053057,16.230322,8.926469,0.873375,1.146361
min,0.000000,0.050000,0.200000,30221.000000,-10.000000,30.000000,2.000000,1.000000
25%,6.000000,0.280000,0.420000,77262.000000,3.000000,37.000000,2.760000,2.060000
50%,12.000000,0.500000,0.600000,127660.500000,17.000000,45.000000,3.540000,3.025000
75%,19.000000,0.730000,0.800000,174811.750000,31.000000,52.000000,4.270000,4.010000
max,25.000000,0.950000,0.990000,219998.000000,45.000000,60.000000,5.000000,5.000000

In [36]:
df.shape

(3000, 20)

In [37]:
df.columns

Index(['Employee_ID', 'Job_Title', 'Industry', 'Country', 'Education_Level',
       'Years_Experience', 'AI_Replacement_Risk', 'Future_Demand_Score',
       'Remote_Work_Possibility', 'Average_Salary_USD', 'Required_Skills',
       'Automation_Level', 'Job_Growth_2030', 'Work_Hours_Per_Week',
       'Company_Size', 'AI_Tool_Usage', 'Performance_Score',
       'Upskilling_Needed', 'Job_Satisfaction', 'Hiring_Trend_2026'],
      dtype='object')

In [38]:
df.dtypes

Employee_ID                 object
Job_Title                   object
Industry                    object
Country                     object
Education_Level             object
Years_Experience             int64
AI_Replacement_Risk        float64
Future_Demand_Score        float64
Remote_Work_Possibility     object
Average_Salary_USD           int64
Required_Skills             object
Automation_Level            object
Job_Growth_2030              int64
Work_Hours_Per_Week          int64
Company_Size                object
AI_Tool_Usage               object
Performance_Score          float64
Upskilling_Needed           object
Job_Satisfaction           float64
Hiring_Trend_2026           object
dtype: object

In [39]:
df.ndim

2

In [40]:
df.empty

False

In [41]:
df.isnull().sum()

Employee_ID                0
Job_Title                  0
Industry                   0
Country                    0
Education_Level            0
Years_Experience           0
AI_Replacement_Risk        0
Future_Demand_Score        0
Remote_Work_Possibility    0
Average_Salary_USD         0
Required_Skills            0
Automation_Level           0
Job_Growth_2030            0
Work_Hours_Per_Week        0
Company_Size               0
AI_Tool_Usage              0
Performance_Score          0
Upskilling_Needed          0
Job_Satisfaction           0
Hiring_Trend_2026          0
dtype: int64

In [43]:
print(df['Industry'])

0       Healthcare
1           Retail
2        Education
3       Government
4        Education
           ...
2995     Education
2996    Healthcare
2997        Energy
2998    Government
2999        Retail
Name: Industry, Length: 3000, dtype: object

# loc and iloc

In [53]:
df.loc[5]

Employee_ID                                          AIJ-100000
Job_Title                                         Data Engineer
Industry                                             Healthcare
Country                                                   Japan
Education_Level                                             PhD
Years_Experience                                              1
AI_Replacement_Risk                                        0.25
Future_Demand_Score                                        0.78
Remote_Work_Possibility                                     Yes
Average_Salary_USD                                       207392
Required_Skills            Python, Communication, Deep Learning
Automation_Level                                            Low
Job_Growth_2030                                               3
Work_Hours_Per_Week                                          37
Company_Size                                         Enterprise
AI_Tool_Usage                                              High
Performance_Score                                          2.08
Upskilling_Needed                                           Yes
Job_Satisfaction                                           3.86
Hiring_Trend_2026                                       Growing
Name: 0, dtype: object

In [54]:
# INDEXING 
df.iloc[0]

Employee_ID                                          AIJ-100000
Job_Title                                         Data Engineer
Industry                                             Healthcare
Country                                                   Japan
Education_Level                                             PhD
Years_Experience                                              1
AI_Replacement_Risk                                        0.25
Future_Demand_Score                                        0.78
Remote_Work_Possibility                                     Yes
Average_Salary_USD                                       207392
Required_Skills            Python, Communication, Deep Learning
Automation_Level                                            Low
Job_Growth_2030                                               3
Work_Hours_Per_Week                                          37
Company_Size                                         Enterprise
AI_Tool_Usage                                              High
Performance_Score                                          2.08
Upskilling_Needed                                           Yes
Job_Satisfaction                                           3.86
Hiring_Trend_2026                                       Growing
Name: 0, dtype: object

In [55]:
df.iloc[0,0]

'AIJ-100000'

In [56]:
df.isnull()

,Employee_ID,Job_Title,Industry,Country,Education_Level,Years_Experience,AI_Replacement_Risk,Future_Demand_Score,Remote_Work_Possibility,Average_Salary_USD,Required_Skills,Automation_Level,Job_Growth_2030,Work_Hours_Per_Week,Company_Size,AI_Tool_Usage,Performance_Score,Upskilling_Needed,Job_Satisfaction,Hiring_Trend_2026
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [57]:
df.isna()

,Employee_ID,Job_Title,Industry,Country,Education_Level,Years_Experience,AI_Replacement_Risk,Future_Demand_Score,Remote_Work_Possibility,Average_Salary_USD,Required_Skills,Automation_Level,Job_Growth_2030,Work_Hours_Per_Week,Company_Size,AI_Tool_Usage,Performance_Score,Upskilling_Needed,Job_Satisfaction,Hiring_Trend_2026
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [60]:
df.fillna(0)

,Employee_ID,Job_Title,Industry,Country,Education_Level,Years_Experience,AI_Replacement_Risk,Future_Demand_Score,Remote_Work_Possibility,Average_Salary_USD,Required_Skills,Automation_Level,Job_Growth_2030,Work_Hours_Per_Week,Company_Size,AI_Tool_Usage,Performance_Score,Upskilling_Needed,Job_Satisfaction,Hiring_Trend_2026
0,AIJ-100000,Data Engineer,Healthcare,Japan,PhD,1,0.25,0.78,Yes,207392,"Python, Communication, Deep Learning",Low,3,37,Enterprise,High,2.08,Yes,3.86,Growing
1,AIJ-100001,Healthcare Analyst,Retail,UK,Bachelor,24,0.73,0.33,No,140785,"Deep Learning, Azure, Communication, TensorFlo...",Low,-5,42,Startup,Moderate,4.54,No,4.23,Growing
2,AIJ-100002,HR Specialist,Education,Canada,High School,21,0.80,0.69,Yes,124800,"Kubernetes, Cloud Computing, TensorFlow, SQL, ...",Medium,-5,57,Startup,Low,3.14,No,3.54,Stable
3,AIJ-100003,Cybersecurity Analyst,Government,UK,Bachelor,5,0.29,0.94,No,199878,"Excel, Kubernetes, Prompt Engineering, Leadership",Medium,7,59,Enterprise,High,3.67,No,4.37,Declining
4,AIJ-100004,Healthcare Analyst,Education,UAE,PhD,20,0.11,0.92,No,178682,"SQL, Leadership, TensorFlow, Cybersecurity",Low,6,34,Startup,High,3.68,No,3.99,Stable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,AIJ-102995,Data Scientist,Education,India,Bachelor,0,0.62,0.27,Hybrid,202565,"Azure, Project Management, Cloud Computing, Cy...",Medium,36,59,Enterprise,Moderate,4.54,Yes,1.27,Stable
2996,AIJ-102996,Data Engineer,Healthcare,UAE,PhD,4,0.52,0.57,Yes,37215,"Communication, PyTorch, Docker",Low,17,45,Startup,Low,2.71,No,2.56,Stable
2997,AIJ-102997,DevOps Engineer,Energy,Pakistan,High School,7,0.72,0.70,No,55179,"TensorFlow, Excel, Python, Docker",Medium,34,35,Startup,Low,4.88,Yes,3.17,Declining
2998,AIJ-102998,Data Scientist,Government,Australia,Bachelor,19,0.82,0.76,Hybrid,125291,"Cybersecurity, Cloud Computing, Deep Learning",Medium,21,47,Startup,Moderate,3.59,Yes,3.78,Stable
2999,AIJ-102999,HR Specialist,Retail,Germany,Master,9,0.68,0.44,No,152792,"Kubernetes, Cybersecurity, Communication",Low,32,44,Medium,Moderate,3.29,No,1.36,Growing

In [64]:
# MERGE THE TWO COLUMNS WITH THE SAME NUMBER OF THE COLUMNS LIKE INT, STRING , FLOAT 

import pandas as pd
# Create DataFrame 1
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Harsh', 'Ran', 'Anna']
})

# Create DataFrame 2
df2 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Age': [12, 15, 17]
})

# Merge the DataFrames
result = pd.merge(df1, df2, on='ID')

print(result)

   ID   Name  Age
0   1  Harsh   12
1   2    Ran   15
2   3   Anna   17

# CONCAT

In [65]:
pd.concat([df1,df2],axis=0)

   ID   Name   Age
0   1  Harsh   NaN
1   2    Ran   NaN
2   3   Anna   NaN
0   1    NaN  12.0
1   2    NaN  15.0
2   3    NaN  17.0